---
- hosts: all
  become: yes
  remote_user: ansible
  tasks:
    - name: Installing httpd
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: Enable web ports
      firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
      become: yes
